name: Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
      - uses: actions/setup-node@v4
        with:
          node-version: '20.18.0'
          cache: 'pnpm'
          cache-dependency-path: 'frontend/pnpm-lock.yaml'

      - name: Install dependencies
        working-directory: ./frontend
        run: pnpm install

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with gradle
        run: |
          ./gradlew --no-daemon -Pnpm.download=false shadowJar
          (echo -n artifactPath=; find build/libs/ -type f) >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          name: balloons.jar
          path: ${{ env.artifactPath }}
          retention-days: 14
          compression-level: 0
